#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xdotool
Version  : 3.20210804.2
Release  : 6
URL      : https://github.com/jordansissel/xdotool/releases/download/v3.20210804.2/xdotool-3.20210804.2.tar.gz
Source0  : https://github.com/jordansissel/xdotool/releases/download/v3.20210804.2/xdotool-3.20210804.2.tar.gz
Summary  : fake keyboard/mouse input, window management, and more
Group    : Development/Tools
License  : BSD-3-Clause
Requires: xdotool-bin = %{version}-%{release}
Requires: xdotool-lib = %{version}-%{release}
Requires: xdotool-license = %{version}-%{release}
Requires: xdotool-man = %{version}-%{release}
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xtst)
Patch1: 0001-Fix-include-lib-dirs-in-pc-file.patch

%description
# `xdotool` - x11 automation tool
`xdotool` lets you simulate keyboard input and mouse activity, move and resize windows, etc. It does this using X11’s XTEST extension and other Xlib functions.

%package bin
Summary: bin components for the xdotool package.
Group: Binaries
Requires: xdotool-license = %{version}-%{release}

%description bin
bin components for the xdotool package.


%package dev
Summary: dev components for the xdotool package.
Group: Development
Requires: xdotool-lib = %{version}-%{release}
Requires: xdotool-bin = %{version}-%{release}
Provides: xdotool-devel = %{version}-%{release}
Requires: xdotool = %{version}-%{release}

%description dev
dev components for the xdotool package.


%package lib
Summary: lib components for the xdotool package.
Group: Libraries
Requires: xdotool-license = %{version}-%{release}

%description lib
lib components for the xdotool package.


%package license
Summary: license components for the xdotool package.
Group: Default

%description license
license components for the xdotool package.


%package man
Summary: man components for the xdotool package.
Group: Default

%description man
man components for the xdotool package.


%prep
%setup -q -n xdotool-3.20210804.2
cd %{_builddir}/xdotool-3.20210804.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1630689683
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}  WITHOUT_RPATH_FIX=1


%install
export SOURCE_DATE_EPOCH=1630689683
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xdotool
cp %{_builddir}/xdotool-3.20210804.2/COPYRIGHT %{buildroot}/usr/share/package-licenses/xdotool/529f17880a19f0a053c551e6ffc15e0f69ad6f89
%make_install PREFIX=/usr INSTALLLIB=/usr/lib64 INSTALLMAN=/usr/share/man

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xdotool

%files dev
%defattr(-,root,root,-)
/usr/include/xdo.h
/usr/lib64/libxdo.so
/usr/lib64/pkgconfig/libxdo.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxdo.so.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xdotool/529f17880a19f0a053c551e6ffc15e0f69ad6f89

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xdotool.1
