#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xdotool
Version  : 3.20160805.1
Release  : 3
URL      : https://github.com/jordansissel/xdotool/releases/download/v3.20160805.1/xdotool-3.20160805.1.tar.gz
Source0  : https://github.com/jordansissel/xdotool/releases/download/v3.20160805.1/xdotool-3.20160805.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: xdotool-bin = %{version}-%{release}
Requires: xdotool-license = %{version}-%{release}
Requires: xdotool-plugins = %{version}-%{release}
BuildRequires : libXinerama-dev
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xtst)

%description
xdotool: Fake input from the mouse and keyboard very easily.
Also supports window manager actions such as moving, activating, and other
actions on windows.
libxdo: C library for doing the same.

%package bin
Summary: bin components for the xdotool package.
Group: Binaries
Requires: xdotool-license = %{version}-%{release}

%description bin
bin components for the xdotool package.


%package dev
Summary: dev components for the xdotool package.
Group: Development
Requires: xdotool-bin = %{version}-%{release}
Provides: xdotool-devel = %{version}-%{release}

%description dev
dev components for the xdotool package.


%package license
Summary: license components for the xdotool package.
Group: Default

%description license
license components for the xdotool package.


%package plugins
Summary: plugins components for the xdotool package.
Group: Default

%description plugins
plugins components for the xdotool package.


%prep
%setup -q -n xdotool-3.20160805.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543894591
make  %{?_smp_mflags} WITHOUT_RPATH_FIX=1


%install
export SOURCE_DATE_EPOCH=1543894591
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xdotool
cp COPYRIGHT %{buildroot}/usr/share/package-licenses/xdotool/COPYRIGHT
%make_install PREFIX=/usr

%files
%defattr(-,root,root,-)
/usr/man/man1/xdotool.1

%files bin
%defattr(-,root,root,-)
/usr/bin/xdotool

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib/libxdo.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xdotool/COPYRIGHT

%files plugins
%defattr(-,root,root,-)
/usr/lib/libxdo.so.3
